### PR TITLE
version.txt fix for the NodeServer Store

### PR DESCRIPTION
**Pull request by ferventgeek**
I believe the reason this won't upgrade from the Polisy NodeServer Store was the miss-match in the server.json and version.txt file. I bumped the server.json verson to 2.0.9 and matched the version.text value.

### CODE REVIEW

**Comment by bpaauwe** [comment]
version.txt isn't used by anything.

I don't see any version mismatch between the store and the node server.  Store says current version is 2.0.8 and node server says current version is 2.0.8. 

You'll only see an update button in the store listing if the version installed is not 2.0.8

**Comment by ferventgeek** [comment]
Ah. Ok, then I'll close the PR and dig into the upgrade issue some more. I'm thinking it's a mix-up in the version number registration and the NodeServer Store. Here's the behavior:

1. Version in the Store is 2.0.8, "James Milne (Einstein.42)" link goes to you.
2. Click "Update" and "Yes" to upload new profile to ISY.
3. Go to Dashboard ->Sonos - Details, shows installed ver 2.0.7
4. Restart Node server, still shows 2.0.7 with the "Update" button in the Store.
5. Restart ISY, Restart Node Server, no change.
6. Nothing in the logs but a regular restart sequence

```
7/6/2022, 19:13:58 [polyglot] info: Sonos(2): Processing command: restart
7/6/2022, 19:13:58 [polyglot] info: Sonos(2): Processing command: connected
7/6/2022, 19:13:58 [polyglot] info: MQTTS: Client Disconnected:
7/6/2022, 19:13:58 [polyglot] info: Sonos(2): NodeServer Disconnected.
7/6/2022, 19:13:58 [polyglot] info: Sonos(2): n002_controller ST set sucessfully to 0 : UOM 2
7/6/2022, 19:13:59 [polyglot] info: Sonos(2): NodeServer Disconnected.
7/6/2022, 19:13:59 [polyglot] info: Sonos(2): n002_controller ST set sucessfully to 0 : UOM 2
7/6/2022, 19:14:01 [polyglot] info: NS: Starting Local NodeServer Sonos profile number 2 :: Version 2.0.7
7/6/2022, 19:14:04 [polyglot] info: MQTTS: Client Connected:
7/6/2022, 19:14:04 [polyglot] info: Sonos(2): Processing command: connected
7/6/2022, 19:14:04 [polyglot] info: Sonos(2): NodeServer Connected.
7/6/2022, 19:14:04 [polyglot] info: Sonos(2): Processing command: customparamsdoc
7/6/2022, 19:14:04 [polyglot] info: NS: Received updated customParamsDoc for Sonos. Updating database.
7/6/2022, 19:14:04 [polyglot] info: Sonos(2): n002_controller ST set sucessfully to 1 : UOM 2
7/6/2022, 19:14:04 [polyglot] info: NS customParamsDoc: Sonos saved sucessfully
```

System version details:
```
Version 2.2.13 Status: Connected
Frontend Version: 2.2.9-5
ISY Version: 5.3.0
```

**Comment by bpaauwe** [comment]
It's probably a PG2 problem.  My guess is that you installed it from the original repository and it's trying to upgrade from the original repository which is version 2.0.7. So even though the store says 2.0.8 is available, PG2 doesn't realize the location of the repository has changed.

You probably have to delete it and re-install it from the new repository to get the new version.

**Comment by ferventgeek** [comment]
Thanks Bob, that was it! thanks for inheriting this project.

**Pull request closed without merging**
